name: Update Live Channels Sniper

on:
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create playlist file from Secret
        # هذا هو السطر الناقص الذي يربط "الخزنة" بالسكربت
        run: echo "${{ secrets.MY_M3U_CONTENT }}" > playlist.m3u

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Sniper Script
        run: python update_channels.py 

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add channels_data.js
          git commit -m "Auto-update channels list" || echo "No changes to commit"
          git push
