// تم ضغط النص المشفر في سطر واحد لضمان عدم وجود مسافات تخرب عملية الفك
var _0xSimoEncoded = 'WwogIHsKICAgICJuYW1lIjogImJlSU4gU1BPUlRTIDEiLAogICAgInVybCI6ICJhSFIwY0hNNkx5OWpiMjlzTFhCcGJtVXRZclZpT1MxbWRYUjJjSEp2Y0dGblpYTktaWFl1ZDI5eWEyVnljM2xrWlhZdmR6MHBZWFJvUFdOc2V4TnpMMlZHUms1VE1sTlRNM2hoVVRCR1ZGUmtWMk5MVUVSTllqWnFWR3RvVURWWk1XMUhPREIyTTNCUWRuRktPSHBoTjJoNVZFcGhMMDVGYmpSNE1HRktiR3hPUlRWSmJtWnNkVVU1ZEZSUlZuQnZha2xHY25KU1IzYzlQUT09LnRzIgogIH0sCiAgewogICAgIm5hbWUiOiAiYmVJTiBTUE9SVFMgMiIsCiAgICAidXJsIjogImhSMGNITTZMeTlpYjI1c0xYQnBibVV0WXJWaU9TMW1kWFIyY0hKdmNHRm5aWE5LWll1ZDI5eWEyVnljM2xrWlhZdmR6MHBZWFJvUFdOc2V4TnpMMlZqWlRrMlZWSlNNVXVtcGlkSE5OV0c1Wk1FOUNUMmRQYWpKclEwRmFaa0ZtV2tkeVVVbDZkbUo0VTJ0cFJsUkRabnBXU0hNdkwydFBVRGN3WnpGNGVEZzVkRk5tZWtOVk5uSlRhRUpTWWpVeFNWUTRjM001TDFFOVBRPT0udHMiCiAgfQpd';

try {
    var _0xSimoData = JSON.parse(atob(_0xSimoEncoded.trim()));
} catch (e) {
    console.error("Base64 Error:", e);
    var _0xSimoData = []; // قائمة فارغة في حال حدوث خطأ لمنع توقف الموقع
}
