name: Update Live Channels Sniper

on:
  schedule:
    - cron: '0 3 * * *' # يعمل تلقائياً الساعة 3 صباحاً كل يوم
  workflow_dispatch: # يتيح لك تشغيله يدوياً بضغطة زر

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Sniper Script
        run: python update_channels.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add channels_data.js
          git commit -m "Auto-update channels list" || exit 0
          git push
