name: Simo Sniper Auto Update

on:
  workflow_dispatch: # للتشغيل اليدوي
  schedule:
    - cron: '0 */6 * * *' # للتشغيل التلقائي كل 6 ساعات

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4 # تم تصحيح المسار هنا ✅
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Simo Sniper
        run: python Simo_Sniper.py # تأكد أن هذا هو نفس اسم ملف السكريبت عندك

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Simo Sniper Bot"
          git add links.json
          git commit -m "Update links.json [🚀]" || exit 0
          git push
